#!/usr/bin/env python
import re
import sys
from pygments.cmdline import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    if '-x' not in sys.argv:
        sys.argv.append('-x')
    sys.exit(main())
